### ISSUE TITLE
react fails in browser

### ISSUE THREAD

**Issue by epiiaddone** [epiiaddone/vocab-quiz#1]
TypeError: Cannot read properties of null (reading 'filter')
    at Z0 (index-C1201VDI.js:75:3238)
    at _u (index-C1201VDI.js:38:16959)
    at jf (index-C1201VDI.js:40:43730)
    at Lf (index-C1201VDI.js:40:39531)
    at Th (index-C1201VDI.js:40:39462)
    at Rl (index-C1201VDI.js:40:39320)
    at Di (index-C1201VDI.js:40:35737)
    at Nf (index-C1201VDI.js:40:34693)
    at x (index-C1201VDI.js:25:1562)
    at MessagePort.Rn (index-C1201VDI.js:25:1930)

**Comment by epiiaddone** [comment]
Bug is here:

const scores = JSON.parse(localStorage.getItem('scores'))
const score = scores.filter(score => score.level === level)

If no local storage then no scores to filter

**Comment by epiiaddone** [comment]
fixed with optional chaining

**Comment by epiiaddone** [comment]
fixed with optional chaining
